import {
  LayoutDashboard,
  BookOpen,
  FileText,
  Calendar,
  Shield,
  Eye,
  EyeOff,
  Plus,
  X,
  Edit2,
  Trash2,
  Check,
  ChevronsUpDown,
  Image as ImageIcon,
  TrendingUp,
  TrendingDown,
  DollarSign,
  Target,
  AlertCircle,
  Lightbulb,
  Filter,
  Grid,
  List,
  LayoutGrid,
  ChevronLeft,
  ChevronRight,
  BarChart3,
  Brain,
  Percent,
  Activity,
  ArrowUpRight,
  ArrowDownRight,
  Save,
  Upload,
  CheckCircle2,
  XCircle,
  ChevronDown,
  Link,
  Download,
  HardDrive,
  FolderSync,
  ToggleLeft,
  ToggleRight,
  Wallet,
  LineChart,
  Clock,
  CalendarDays,
  Calculator,
  CornerDownLeft,
  GripVertical,
  Expand,
  SlidersHorizontal,
  ArrowUpDown,
  Sun,
  Moon,
  PanelLeft,
  Flame,
  ClipboardPaste,
  ZoomIn,
  Send,
  ImagePlus,
  StickyNote,
  Box,
  Search,
  ArrowLeft,
  Database,
  Settings,
  Scale,
  Layers,
  ShieldCheck,
  Zap,
  AlertTriangle,
  Star,
  Flag,
  Bookmark,
  Lock,
  Crosshair,
  Rocket,
  Award,
  Bell,
  Gem,
  Anchor,
  Compass,
  Swords,
  Smile,
  Palette,
  Quote,
  RefreshCw,
  ListChecks,
  Dumbbell,
  Coffee,
  Heart,
  type LucideIcon,
} from 'lucide-react';
import type { NoticeType } from '../types';

export const NOTICE_TYPE_META: Record<NoticeType, {
  label: string;
  shortLabel: string;
  tabLabel: string;
  headerIcon: LucideIcon;
  badge: string;
  cardRing: string;
  calloutLabel: string;
  callout: string;
  calloutIcon: LucideIcon;
}> = {
  // Insight listed first so the "Add Market Notice" type toggle shows
  // Price Action Insight on the left and Anti-Mistake / Trap on the
  // right — matching the Market Notices page, where Price Action
  // Insights is the left column and Anti-Mistakes & Traps is the right.
  insight: {
    label: 'Price Action Insight',
    shortLabel: 'Insight',
    tabLabel: 'Price Action Insights',
    headerIcon: Eye,
    badge: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/30',
    cardRing: 'border-cyan-500/20 hover:border-cyan-500/50',
    calloutLabel: 'How To Use This',
    callout: 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300',
    calloutIcon: Lightbulb,
  },
  mistake: {
    label: 'Anti-Mistake / Trap',
    shortLabel: 'Trap',
    tabLabel: 'Anti-Mistakes & Traps',
    headerIcon: AlertTriangle,
    badge: 'bg-rose-500/10 text-rose-400 border-rose-500/30',
    cardRing: 'border-rose-500/20 hover:border-rose-500/50',
    calloutLabel: 'Prevention Rule',
    callout: 'bg-amber-500/10 border-amber-500/30 text-amber-300',
    calloutIcon: ShieldCheck,
  },
};

